### ISSUE TITLE
Şuanda yazılan aslında bir issue değil ama bir yandanda issue

### ISSUE THREAD

**Issue by co3moz** [frknbasaran/focusify#1]
Panpa paradoksu çözün.. ** graps a popcorn

**Comment by co3moz** [comment]
zaa

**Comment by erayarslan** [comment]
liseli

**Comment by co3moz** [comment]
Bu issue kapanmış bir issue ama bir yandan da kapanmış bir issue değil.

**Comment by frknbasaran** [comment]
hi dude :)
shut the fuck up please.
thanks for feedback.

**Comment by co3moz** [comment]
Biri gavurca yazdı çevirin..
** eating his buttt..

**Comment by kadiryaka** [comment]
Issue görmesek issue diye kitleyeceksiniz.
